#runtime: java11
#env: standard
#runtime_config:
#  jdk: openjdk11
#env_variables:
#  SPRING_PROFILES_ACTIVE: "production"
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#manual_scaling:
#  instances: 1


runtime: java
env : flex
#inbound_services:
#  - warmup
#derived_file_type:
#  - java_precompiled
#
#runtime_config:
#  jdk: openjdk8

handlers:
  - url: /.*
    script: this field is required, but ignored

service_account: team5-143@rice-comp-539-spring-2022.iam.gserviceaccount.com

resources:
  memory_gb: 4