#runtime: java11
#env: standard
#runtime_config:
#  jdk: openjdk11
#env_variables:
#  SPRING_PROFILES_ACTIVE: "production"
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#manual_scaling:
#  instances: 1


runtime: java
env : flex
inbound_services:
  - warmup
derived_file_type:
  - java_precompiled

runtime_config:
  jdk: openjdk8

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10